version: "3.3"
services:
  backend:
    build: .
    container_name: backend
    hostname: backend
    ports:
      - "8000:5000"
    volumes:
      - .:/app
    environment:
      FLASK_DEBUG: "true"
    tty: true
    depends_on:
      - database
  
  redis:
    container_name: redis-business
    image: "redis:alpine"
  
  database:
    image: "postgres:16"
    container_name: database
    hostname: database
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=business
      - POSTGRES_PASSWORD=pw
      - POSTGRES_DB=business_db

volumes:
  postgres_data: 

