version: "3.3"
services:
  backend:
    build: .
    container_name: backend
    hostname: backend
    ports:
      - "8000:5000"
    volumes:
      - .:/app
    environment:
      FLASK_DEBUG: "true"
      POSTGRES_PASSWORD: "postgres"
      DATABASE_URL: "postgresql://postgres:postgres@database:5432"
    tty: true
    depends_on:
      - database

    worker:
      build: .
      command: celery -A main.celery worker --loglevel=info
      container_name: worker-1
      hostname: worker-1
      depends_on:
        - redis
        - backend
  
  redis:
    container_name: redis-business
    image: "redis:alpine"
  
  database:
    image: "postgres:16"
    container_name: database
    hostname: database
    ports:
      - 5432:5432
    volumes:
      - psql_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=business_db

volumes:
  psql_data: 

