"""first migration

Revision ID: 55f0f778489e
Revises: 
Create Date: 2024-01-20 16:19:58.757277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55f0f778489e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('metrics',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('business_uid', sa.UUID(), nullable=False),
    sa.Column('cashflow', sa.Float(), nullable=True),
    sa.Column('ask_price', sa.Float(), nullable=False),
    sa.Column('gross_revenue', sa.Float(), nullable=True),
    sa.Column('ebitda', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['business_uid'], ['business.uid'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('metrics')
    op.drop_table('business')
    # ### end Alembic commands ###
