"""add metrics, add deal box

Revision ID: 7f69edf4e8d0
Revises: b29180ab7e07
Create Date: 2024-01-29 11:52:03.602226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f69edf4e8d0'
down_revision = 'b29180ab7e07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deal_box',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('valuation_low', sa.Float(), nullable=True),
    sa.Column('valuation_high', sa.Float(), nullable=True),
    sa.Column('revenue_low', sa.Float(), nullable=True),
    sa.Column('revenue_high', sa.Float(), nullable=True),
    sa.Column('profit_low', sa.Float(), nullable=True),
    sa.Column('profit_high', sa.Float(), nullable=True),
    sa.Column('margin', sa.Float(), nullable=True),
    sa.Column('sector', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('seller_type', sa.String(), nullable=True),
    sa.Column('geography', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('scale', sa.Integer(), nullable=True),
    sa.Column('advantages', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('investor', sa.Boolean(), nullable=True),
    sa.Column('multiple_low', sa.Float(), nullable=True),
    sa.Column('multiple_high', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    with op.batch_alter_table('metrics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valuation', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('revenue', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('sector', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('geography', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('scale', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('advantages', sa.ARRAY(sa.String()), nullable=True))
        batch_op.add_column(sa.Column('investor', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('multiple', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('metrics', schema=None) as batch_op:
        batch_op.drop_column('multiple')
        batch_op.drop_column('investor')
        batch_op.drop_column('advantages')
        batch_op.drop_column('scale')
        batch_op.drop_column('geography')
        batch_op.drop_column('sector')
        batch_op.drop_column('revenue')
        batch_op.drop_column('valuation')

    op.drop_table('deal_box')
    # ### end Alembic commands ###
