"""add new portfolio and relationship tables

Revision ID: a9cab91f0a33
Revises: ef3d337195cf
Create Date: 2024-07-02 22:55:28.972629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9cab91f0a33'
down_revision = 'ef3d337195cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('portfolio_business',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('portfolio_uid', sa.UUID(), nullable=False),
    sa.Column('business_uid', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['business_uid'], ['business.uid'], onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['portfolio_uid'], ['portfolio.uid'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('uid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('portfolio_business')
    op.drop_table('portfolio')
    # ### end Alembic commands ###
