"""add deal box table

Revision ID: b29180ab7e07
Revises: 55f0f778489e
Create Date: 2024-01-29 01:00:20.968023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b29180ab7e07'
down_revision = '55f0f778489e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business', schema=None) as batch_op:
        batch_op.add_column(sa.Column('biz_type', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business', schema=None) as batch_op:
        batch_op.drop_column('biz_type')

    # ### end Alembic commands ###
